mode = "dark"

accent = "#c9a593"
selection = "#403732"
muted = "#69625f"

background = "#1f130e"
dark_background = "#170e0a"
darker_background = "#100a07"
lighter_background = "#352b26"

foreground = "#d7cdb1"
dark_foreground = "#9f9883"
light_foreground = "#ddd4bd"
bright_foreground = "#e1dac4"

red = "#c7a291"
yellow = "#d7c69a"
orange = "#cdaf94"
green = "#cdbc92"
cyan = "#d1bf97"
blue = "#c9a593"
magenta = "#d0ab9a"
brown = "#716051"

bright_red = "#edc3ad"
bright_yellow = "#edd37e"
bright_green = "#e3c976"
bright_cyan = "#e8cb7c"
bright_blue = "#edc5ad"
bright_magenta = "#f0c7b1"
